import ApiError from "./ApiError.js";
import { configureCloudinary, isCloudinaryConfigured } from "../config/cloudinary.js";

/**
 * Signed direct-to-Cloudinary upload parameters (scope §10.3).
 *
 * The browser uploads straight to Cloudinary rather than through this API, because
 * agents upload 8MB phone photos over connections that drop and proxying would cross
 * the network twice. A Cloudinary signature is a bearer capability, so everything
 * here exists to keep it narrow: it authorises exactly one listing's folder, and
 * nothing else.
 */

/** The parent folder every listing's assets live under. */
const ROOT_FOLDER = "properties";

/** Image formats the upload will accept. Signed, so the browser cannot widen it. */
export const ALLOWED_FORMATS = ["jpg", "jpeg", "png", "webp", "avif"];

/**
 * Eager transformation producing the gallery thumbnail on upload.
 *
 * No watermark overlay: §4.2 asks for one, but there is no client logo asset yet, and
 * pointing `watermarkedUrl` at an unwatermarked file would be worse than leaving it
 * unset. See the design doc's Deferred section.
 */
export const EAGER_TRANSFORMATION = "c_fill,w_400,h_300,q_auto,f_auto";

/**
 * Advisory size ceiling, enforced in the browser before a signature is requested.
 *
 * Not part of the signature: Cloudinary's `max_file_size` upload parameter requires an
 * authenticated upload preset, and signing a parameter the endpoint does not accept
 * makes every upload fail with "Invalid Signature". The real check is server-side, at
 * registration, where the byte count is read back from Cloudinary.
 */
export const MAX_FILE_SIZE = 15 * 1024 * 1024;

/** A reference is server-generated, so anything outside this is a bug, not input. */
const SAFE_REFERENCE = /^[A-Za-z0-9-]+$/;

/**
 * The Cloudinary folder holding one listing's assets.
 *
 * Takes: reference (string) — the listing's REF code.
 * Returns: the folder path, e.g. "properties/REF1042".
 * Throws: ApiError 500 when the reference could escape its parent folder. References
 *         are generated by the server, so this is an internal invariant — but a slash
 *         or a ".." in a folder name would let one listing's signature write over
 *         another listing's assets.
 */
export function folderForListing(reference) {
  if (!reference || !SAFE_REFERENCE.test(reference)) {
    throw new ApiError(500, "Listing reference is not safe to use as a folder name");
  }

  return `${ROOT_FOLDER}/${reference}`;
}

/**
 * Whether a Cloudinary public_id belongs to a given listing.
 *
 * Takes: publicId (string) — as returned by Cloudinary; reference (string).
 * Returns: true when the id sits inside that listing's folder.
 */
export function isInListingFolder(publicId, reference) {
  if (typeof publicId !== "string" || publicId.length === 0) return false;

  let folder;

  try {
    folder = folderForListing(reference);
  } catch {
    return false;
  }

  // The trailing slash matters: a bare startsWith(folder) also matches
  // "properties/REF1042extra/...", which is a different listing's folder entirely.
  return publicId.startsWith(`${folder}/`);
}

/**
 * Builds everything the browser needs to upload one image, and nothing more.
 *
 * The signed parameter set is a contract with frontend/src/lib/uploadMedia.js:
 * Cloudinary recomputes the signature over the parameters it actually receives, so
 * the browser must send exactly these and no others. Adding a parameter here without
 * adding it there — or the reverse — fails every upload with "Invalid Signature".
 *
 * Takes: reference (string) — the listing's REF code.
 * Returns: { timestamp, signature, apiKey, cloudName, folder, uploadUrl,
 *            allowedFormats, maxFileSize, eager }.
 * Throws: ApiError 503 when Cloudinary is not configured.
 */
export function buildUploadSignature(reference) {
  if (!isCloudinaryConfigured()) {
    throw new ApiError(503, "Image uploads are not configured");
  }

  const cloudinary = configureCloudinary();
  const folder = folderForListing(reference);

  // Cloudinary rejects signatures older than roughly an hour on its own, so there is
  // no separate expiry parameter to set.
  const timestamp = Math.round(Date.now() / 1000);

  const signature = cloudinary.utils.api_sign_request(
    {
      timestamp,
      folder,
      allowed_formats: ALLOWED_FORMATS.join(","),
      eager: EAGER_TRANSFORMATION,
    },
    process.env.CLOUDINARY_API_SECRET
  );

  return {
    timestamp,
    signature,
    // The cloud name and API key are public by design; the secret never leaves here.
    apiKey: process.env.CLOUDINARY_API_KEY,
    cloudName: process.env.CLOUDINARY_CLOUD_NAME,
    folder,
    uploadUrl: `https://api.cloudinary.com/v1_1/${process.env.CLOUDINARY_CLOUD_NAME}/image/upload`,
    allowedFormats: ALLOWED_FORMATS,
    maxFileSize: MAX_FILE_SIZE,
    eager: EAGER_TRANSFORMATION,
  };
}
